import { chatWithAI } from '../../services/aiService.js'
import { GeneratedModule } from '../../models/GeneratedModule.js'

const SYSTEM_PROMPT = `Ты senior fullstack dev для AI Viral Studio. Стек: React 18, Vite, Tailwind 3.4, Node.js, Express, MongoDB, ES modules. Пиши production-ready: mobile-first, CSS-переменные, glassmorphism, error handling, i18n-ready. НЕ используй mock. Верни ТОЛЬКО JSON без markdown: {"frontend":"код","backend":"код","tests":"код"}`

export async function generateModule(spec, userId = null) {
    const prompt = buildPrompt(spec)
    const ai = await chatWithAI(prompt, [], 'ru', { userRole: 'owner', userId })
    const reply = ai?.reply || ai?.text || ''
    let parsed = { frontend: '', backend: '', tests: '' }
    try {
        const jsonMatch = reply.match(/\{[\s\S]*\}/)
        const json = jsonMatch ? JSON.parse(jsonMatch[0]) : JSON.parse(reply)
        parsed = {
            frontend: json.frontend || '',
            backend: json.backend || '',
            tests: json.tests || '',
        }
    } catch (err) {
        console.error('[omegaDevStudio] failed to parse AI JSON:', err.message)
        parsed = fallbackCode(spec)
    }

    const moduleDoc = await GeneratedModule.create({
        name: spec.name || 'Untitled Module',
        type: spec.type || 'Fullstack',
        spec,
        frontendCode: parsed.frontend,
        backendCode: parsed.backend,
        testCode: parsed.tests,
        status: 'draft',
        createdBy: 'OMEGA',
        createdById: userId,
    })

    return {
        moduleId: moduleDoc._id,
        status: 'draft',
        ...parsed,
    }
}

export async function listModules(userId = null, query = {}) {
    const filter = userId ? { createdById: userId } : {}
    return GeneratedModule.find({ ...filter, ...query }).sort({ createdAt: -1 }).lean()
}

export async function getModule(id) {
    return GeneratedModule.findById(id).lean()
}

export async function approveModule(id) {
    return GeneratedModule.findByIdAndUpdate(id, { status: 'approved' }, { new: true }).lean()
}

export async function deployModule(id) {
    const mod = await GeneratedModule.findById(id).lean()
    if (!mod) throw new Error('Module not found')
    if (mod.status !== 'approved') throw new Error('Module must be approved before deploy')
    // Only write to approved folders
    const fs = await import('fs/promises')
    const path = await import('path')
    const { fileURLToPath } = await import('url')
    const __filename = fileURLToPath(import.meta.url)
    const projectRoot = path.resolve(path.dirname(__filename), '../../..')
    const safeName = String(mod.name).replace(/[^a-zA-Z0-9_-]/g, '_')
    const timestamp = Date.now()

    const files = []
    if (mod.frontendCode) {
        const frontendDir = path.join(projectRoot, 'frontend/src/omega-generated')
        await fs.mkdir(frontendDir, { recursive: true })
        const filePath = path.join(frontendDir, `${safeName}_${timestamp}.jsx`)
        await fs.writeFile(filePath, mod.frontendCode, 'utf8')
        files.push(filePath)
    }
    if (mod.backendCode) {
        const backendDir = path.join(projectRoot, 'backend/omega-generated')
        await fs.mkdir(backendDir, { recursive: true })
        const filePath = path.join(backendDir, `${safeName}_${timestamp}.js`)
        await fs.writeFile(filePath, mod.backendCode, 'utf8')
        files.push(filePath)
    }
    if (mod.testCode) {
        const backendDir = path.join(projectRoot, 'backend/omega-generated')
        await fs.mkdir(backendDir, { recursive: true })
        const filePath = path.join(backendDir, `${safeName}_${timestamp}.test.js`)
        await fs.writeFile(filePath, mod.testCode, 'utf8')
        files.push(filePath)
    }

    await GeneratedModule.findByIdAndUpdate(id, { status: 'deployed' })
    return { moduleId: id, files, status: 'deployed' }
}

function buildPrompt(spec) {
    return `Сгенерируй production-ready модуль для AI Viral Studio.

Название: ${spec.name || 'Untitled'}
Тип: ${spec.type || 'Fullstack'}
Технологии: ${(spec.tech || []).join(', ') || 'React, Vite, Tailwind, Node.js, Express, MongoDB'}
Фичи: ${(spec.features || []).join(', ') || 'base'}
Дизайн: ${spec.design || 'Glassmorphism'}

Требования:
- Frontend: React 18 компонент, Vite, Tailwind 3.4, mobile-first, CSS-переменные, glassmorphism, error handling, i18n-ready.
- Backend: Node.js + Express + MongoDB, ES modules, REST endpoint, валидация, error handling.
- Tests: базовые unit/integration тесты для основной логики.

Верни JSON: {"frontend":"...","backend":"...","tests":"..."}.`
}

function fallbackCode(spec) {
    const name = spec.name || 'UntitledModule'
    return {
        frontend: `// ${name} — generated by OMEGA DevStudio\nexport default function ${name}() { return <div className="glass-card p-6">${name}</div> }`,
        backend: `// ${name} — generated by OMEGA DevStudio\nimport express from 'express'\nconst router = express.Router()\nexport default router`,
        tests: `// ${name} — generated by OMEGA DevStudio\nimport { test, expect } from 'vitest'\ntest('${name} works', () => { expect(true).toBe(true) })`,
    }
}
