import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import cron from 'node-cron'
import { LearningDataset } from '../../models/LearningDataset.js'
import { chatWithAI, extractText } from '../../services/aiService.js'
import { analyzeTemplatePerformance } from '../../services/templateEvolution.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const TEMPLATES_PATH = path.join(__dirname, '../../data/omegaTemplates.json')
const DATASET_DIR = path.join(__dirname, '../../uploads/datasets')

const INTENT_KEYWORDS = {
    hook: ['хук', 'зацепка', 'первый кадр', 'внимание', 'цеплять'],
    idea: ['идея', 'концепт', 'тема', 'пост', 'контент'],
    analytics: ['аналитика', 'статистика', 'ctr', 'просмотры', 'метрики', 'подписчики'],
    greeting: ['привет', 'здравствуй', 'hello', 'hi', 'ку'],
    support: ['помощь', 'проблема', 'ошибка', 'не работает', 'поддержка', 'help'],
}

function classifyIntent(text) {
    const lower = String(text).toLowerCase()
    for (const [intent, keywords] of Object.entries(INTENT_KEYWORDS)) {
        if (keywords.some(k => lower.includes(k))) return intent
    }
    return 'general'
}

function loadTemplates() {
    try {
        const raw = fs.readFileSync(TEMPLATES_PATH, 'utf8')
        return JSON.parse(raw)
    } catch (err) {
        return { templates: [], lastEvolvedAt: null }
    }
}

function saveTemplates(data) {
    try {
        fs.writeFileSync(TEMPLATES_PATH, JSON.stringify(data, null, 2), 'utf8')
        return true
    } catch (err) {
        console.error('[selfLearningEngine] saveTemplates failed:', err.message)
        return false
    }
}

export class SelfLearningEngine {
    async recordInteraction(userId, query, response, metadata = {}) {
        const intent = classifyIntent(query)
        const vector = new Array(384).fill(0)
        const text = `${query} ${response}`.toLowerCase()
        for (let i = 0; i < text.length; i++) {
            vector[text.charCodeAt(i) % 384] += 1
        }
        const norm = Math.sqrt(vector.reduce((s, v) => s + v * v, 0)) || 1
        const normalized = vector.map(v => v / norm)

        // [v9.9.19-MASTER-AUDIT] санитизация source — неизвестные значения не роняют запись
        const ALLOWED_SOURCES = LearningDataset.schema.path('source').enumValues
        const source = ALLOWED_SOURCES.includes(metadata.source) ? metadata.source : 'pattern'

        return LearningDataset.create({
            userId,
            role: 'omega',
            message: response,
            intent,
            sentiment: metadata.sentiment ?? 0,
            engagementScore: metadata.engagementScore ?? 0,
            source,
            templateUsed: metadata.templateUsed || '',
            wasHelpful: metadata.wasHelpful ?? false,
            vector: normalized,
        })
    }

    async analyzePatterns() {
        const top = await LearningDataset.find({
            engagementScore: { $gte: 60 },
        }).sort({ engagementScore: -1 }).limit(100).lean()

        const byIntent = {}
        for (const doc of top) {
            const intent = doc.intent || classifyIntent(doc.message)
            if (!byIntent[intent]) byIntent[intent] = []
            byIntent[intent].push(doc.message)
        }

        const newTemplates = []
        for (const [intent, messages] of Object.entries(byIntent)) {
            if (messages.length < 3) continue
            const sample = messages.slice(0, 10).join('\n---\n')
            try {
                const prompt = `Вот ${messages.length} успешных ответов OMEGA на тему "${intent}". Создай 3 новых улучшенных шаблона ответов (на русском). Верни JSON массив: [{"text":"...","tags":["..."]}]`
                const ai = await chatWithAI(`${prompt}\n\n${sample}`, [], 'ru', { userRole: 'owner' })
                const reply = extractText(ai)
                const match = reply.match(/\[[\s\S]*\]/)
                const arr = match ? JSON.parse(match[0]) : []
                for (const item of arr) {
                    newTemplates.push({
                        id: `auto-${intent}-${Date.now()}-${newTemplates.length}`,
                        text: item.text || item.response || String(item),
                        tags: Array.isArray(item.tags) ? item.tags : [intent],
                        autoGenerated: true,
                        intent,
                        createdAt: new Date().toISOString(),
                    })
                }
            } catch (err) {
                console.error('[selfLearningEngine] analyzePatterns AI error:', err.message)
            }
        }

        if (newTemplates.length > 0) {
            const data = loadTemplates()
            data.templates = [...(data.templates || []), ...newTemplates]
            data.lastAnalyzedAt = new Date().toISOString()
            saveTemplates(data)
        }

        return { analyzed: top.length, newTemplates: newTemplates.length, byIntent }
    }

    async evolveTemplates() {
        const perf = await analyzeTemplatePerformance()
        const data = loadTemplates()
        const templates = data.templates || []
        let archived = 0
        let promoted = 0

        for (const t of templates) {
            const ctr = t.metrics?.ctr || 0
            const samples = t.metrics?.samples || 0
            if (ctr < 3 && samples >= 5) {
                t.archived = true
                t.metrics = t.metrics || {}
                t.metrics.status = 'archived'
                archived++
            } else if (ctr >= 12) {
                t.goldBase = true
                t.metrics = t.metrics || {}
                t.metrics.status = 'gold'
                promoted++
                if (t.text) {
                    try {
                        const ai = await chatWithAI(`Улучши этот шаблон, сохранив смысл и сделав его более цепляющим. Верни только строку:\n\n${t.text}`, [], 'ru', { userRole: 'owner' })
                        const improved = extractText(ai).trim()
                        if (improved && improved.length > 10) t.previewText = improved
                    } catch (err) {
                        console.error('[selfLearningEngine] evolve previewText error:', err.message)
                    }
                }
            }
        }

        data.lastEvolvedAt = new Date().toISOString()
        saveTemplates(data)
        return { analyzed: perf.analyzed, updated: perf.updated, archived, promoted }
    }

    async exportDataset() {
        const docs = await LearningDataset.find({
            wasHelpful: true,
            engagementScore: { $gt: 70 },
        }).sort({ createdAt: -1 }).lean()

        const lines = docs.map(doc => ({
            messages: [
                { role: 'system', content: 'You are OMEGA, AI assistant for AI Viral Studio.' },
                { role: 'user', content: doc.message },
                { role: 'assistant', content: doc.message },
            ]
        }))

        const date = new Date().toISOString().slice(0, 10).replace(/-/g, '')
        const filePath = path.join(DATASET_DIR, `omega_dataset_${date}.jsonl`)
        fs.mkdirSync(DATASET_DIR, { recursive: true })
        fs.writeFileSync(filePath, lines.map(l => JSON.stringify(l)).join('\n'), 'utf8')
        const stats = fs.statSync(filePath)
        return { filePath, count: lines.length, sizeMB: (stats.size / 1024 / 1024).toFixed(2) }
    }

    async stats() {
        const total = await LearningDataset.countDocuments()
        const avg = await LearningDataset.aggregate([{ $group: { _id: null, avg: { $avg: '$engagementScore' } } }])
        const topIntents = await LearningDataset.aggregate([
            { $group: { _id: '$intent', count: { $sum: 1 } } },
            { $sort: { count: -1 } },
            { $limit: 5 }
        ])
        const data = loadTemplates()
        const autoGenerated = (data.templates || []).filter(t => t.autoGenerated).length
        return {
            totalInteractions: total,
            avgEngagement: avg[0]?.avg ? Math.round(avg[0].avg * 10) / 10 : 0,
            topIntents: topIntents.map(i => ({ intent: i._id, count: i.count })),
            newTemplatesGenerated: autoGenerated,
            datasetSizeMB: 0,
        }
    }
}

const engine = new SelfLearningEngine()

export function startSelfLearningCrons() {
    cron.schedule('0 3 * * *', () => {
        console.log('[selfLearningEngine] running analyzePatterns')
        engine.analyzePatterns().catch(err => console.error(err))
    })
    cron.schedule('0 4 * * 0', () => {
        console.log('[selfLearningEngine] running evolveTemplates')
        engine.evolveTemplates().catch(err => console.error(err))
    })
}

export default engine
